'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'tr' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  toggleLanguage: () => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  tr: {
    // Header
    'nav.home': 'Ana Sayfa',
    'nav.about': 'Hakkımızda',
    'nav.services': 'Hizmetler',
    'nav.beforeAfter': 'Önce/Sonra',
    'nav.contact': 'İletişim',
    
    // Hero
    'hero.badge': 'Türkiye\'nin En Güvenilen Saç Kliniği',
    'hero.title': 'Hayalinizdeki Saçlara',
    'hero.titleHighlight': 'Kavuşun',
    'hero.subtitle': 'Profesyonel saç ekimi ve saç bakım hizmetleri ile doğal, kalıcı sonuçlar. Hayalinizdeki saçlara birlikte ulaşalım.',
    'hero.consultation': 'Ücretsiz Muayene',
    'hero.gallery': 'Galeriyi İncele',
    'hero.cta.consultation': 'Ücretsiz Muayene',
    'hero.cta.whatsapp': 'WhatsApp İletişim',
    'hero.stats.customers': '3800+ Mutlu Hasta',
    'hero.stats.customersDesc': 'Başarılı operasyonlar',
    'hero.stats.experience': '8+ Yıl Deneyim',
    'hero.stats.experienceDesc': 'Uzman kadro',
    'hero.stats.success': '%98 Başarı Oranı',
    'hero.stats.successDesc': 'Kaliteli sonuçlar',
    
    // Hero Form
    'hero.form.title': 'Ücretsiz Muayene',
    'hero.form.name': 'Adınız',
    'hero.form.surname': 'Soyadınız',
    'hero.form.phone': 'Telefon',
    'hero.form.email': 'E-posta',
    'hero.form.message': 'Mesajınız (opsiyonel)',
    'hero.form.submit': 'Ücretsiz Muayene',
    
    // Form
    'form.title': 'Ücretsiz Muayene',
    'form.subtitle': 'Ücretsiz danışmanlık için form doldurun',
    'form.name': 'Adınız',
    'form.surname': 'Soyadınız',
    'form.phone': 'Telefon',
    'form.email': 'E-posta',
    'form.message': 'Mesajınız (opsiyonel)',
    'form.submit': 'Ücretsiz Muayene',
    'form.sending': 'Gönderiliyor...',
    'form.success': 'Mesajınız başarıyla gönderildi! Size en kısa sürede dönüş yapacağız.',
    'form.error': 'Bir hata oluştu. Lütfen tekrar deneyin.',
    'form.errorPhone': 'Bir hata oluştu. Lütfen telefon ile iletişime geçin.',
    'form.securityMessage': '✅ %100 güvenli • 📞 24 saat dönüş • 🎯 Kişisel çözüm',
    
    // Buttons
    'buttons.getInfo': 'Bilgi Al',
    'buttons.bookAppointment': 'Randevu Al',
    'buttons.infoAndAppointment': 'Bilgi & Randevu Al',
    'buttons.callNow': 'Hemen Ara',
    'buttons.whatsapp': 'WhatsApp',
    'buttons.learnMore': 'Daha Fazla Bilgi',
    
    // Stats
    'stats.customers': 'Mutlu Müşteri',
    'stats.experience': 'Yıl Deneyim',
    'stats.satisfaction': 'Müşteri Memnuniyeti',
    'stats.support': 'Destek',
    
    // Services Page
    'services.title': 'Hizmetlerimiz',
    'services.subtitle': 'Modern teknikler ve deneyimli kadromuzla size en iyi saç ekimi hizmetlerini sunuyoruz.',
    'services.cta.title': 'Hangi Tedavi Size Uygun?',
    'services.cta.subtitle': 'Uzman doktorlarımızdan ücretsiz analiz alın',
    'services.expertsTitle': 'Uzman Hizmetlerimiz',
    'services.expertsDesc': 'Size en uygun tedavi yöntemini belirlemek için detaylı analiz gerçekleştiriyoruz',
    'services.process.title': 'Tedavi Sürecimiz',
    'services.process.subtitle': 'Adım adım profesyonel yaklaşım',
    'services.faq.title': 'Sık Sorulan Sorular',
    'services.faq.subtitle': 'Merak ettikleriniz',
    'services.fue.title': 'SAFIR FUE Saç Ekimi',
    'services.fue.desc': 'Folliküler Unit Extraction yöntemi ile doğal saç ekimi',
    'services.dhi.title': 'DHI Saç Ekimi',
    'services.dhi.desc': 'Direct Hair Implantation ile gelişmiş saç ekimi',
    'services.prp.title': 'PRP Tedavisi',
    'services.prp.desc': 'Platelet Rich Plasma ile saç güçlendirme',
    'services.mesotherapy.title': 'Mezoterapi',
    'services.mesotherapy.desc': 'Saç derisi için özel vitamin kokteyli',
    'services.beard.title': 'Sakal Ekimi',
    'services.beard.desc': 'Erkekler için profesyonel sakal ve bıyık ekimi',
    'services.eyebrow.title': 'Kaş Ekimi',
    'services.eyebrow.desc': 'Kadın ve erkekler için kaş yoğunlaştırma ve şekillendirme',
    'services.hybrid.title': 'HYBRID FUE+DHI',
    'services.hybrid.desc': 'FUE ve DHI tekniklerinin birleşimi ile en gelişmiş saç ekimi',
    'services.stemCell.title': 'Kök Hücre Tedavisi',
    'services.stemCell.desc': 'Saç follüküllerini güçlendiren kök hücre tedavisi',
    'services.exosome.title': 'Eksozom',
    'services.exosome.desc': 'Yenilikçi eksozom tedavisi ile saç rejenerasyonu',
    'services.process.step1.title': 'Transfer hizmeti\n(İsteğe Bağlı)',
    'services.process.step1.desc': 'Havalimanı karşılama ve transfer hizmeti',
    'services.process.step2.title': 'Konsültasyon',
    'services.process.step2.desc': 'Ücretsiz muayene ve analiz',
    'services.process.step3.title': 'Planlama',
    'services.process.step3.desc': 'Kişiselleştirilmiş tedavi planı',
    'services.process.step4.title': 'Uygulama',
    'services.process.step4.desc': 'Profesyonel saç ekimi işlemi',
    'services.process.step5.title': 'Otel hizmeti  (İsteğe Bağlı)',
    'services.process.step5.desc': 'Konforlu konaklama imkanı',
    'services.process.step6.title': 'Takip',
    'services.process.step6.desc': 'Sürekli destek ve kontrol',
    'services.faq.question1': 'Saç ekimi ağrılı mı?',
    'services.faq.question2': 'Sonuçlar ne zaman görülür?',
    'services.faq.question3': 'Saç ekimi kalıcı mı?',
    'services.faq.question4': 'Hangi teknik daha iyi?',
    'services.badge': 'Hizmetlerimiz',
    'services.mainTitle1': 'SAÇ EKİMİ',
    'services.mainTitle2': 'HİZMETLERİ',
    'services.mainSubtitle': 'Modern teknoloji ve uzman ekibimizle size en iyi hizmeti sunuyoruz',
    'services.gridTitle': 'Hizmet Seçeneklerimiz',
    'services.gridSubtitle': 'Size en uygun saç ekimi yöntemini birlikte belirleyelim',
    'services.popular': 'Popüler',
    'services.duration': 'Süre',
    'services.recovery': 'İyileşme',
    'services.success': 'Başarı',
    'services.details': 'Detaylar',
    'services.processTitle': 'Süreç Nasıl İşler?',
    'services.processSubtitle': 'Saç ekimi sürecini 6 adımda tamamlıyoruz',
    'services.ctaTitle': 'Hayalinizdeki Saçlara Kavuşun',
    'services.ctaSubtitle': 'Uzman ekibimizden ücretsiz konsültasyon alın',
    'services.recovery.fue': '7-10 gün',
    'services.recovery.dhi': '5-7 gün',
    'services.recovery.prp': '1-2 gün',
    'services.recovery.mesotherapy': 'Yok',
    'services.recovery.beard': '5-7 gün',
    'services.recovery.eyebrow': '3-5 gün',
    'services.recovery.hybrid': '5-10 gün',
    'services.recovery.stemCell': '1-3 gün',
    'services.recovery.exosome': 'Yok',
    
    // Modal translations
    'modal.description': 'Açıklama',
    'modal.advantages': 'Avantajlar',
    'modal.process': 'İşlem Süreci',
    'modal.suitable': 'Kimler İçin Uygun',
    'modal.idealCandidates': 'İdeal Adaylar',
    'modal.results': 'Sonuçlar',
    
    // FUE Hair Transplant Details
    'services.fue.title.tagline': 'En Popüler ve Güvenilir Yöntem',
    'services.fue.title.fullDesc': 'FUE (Follicular Unit Extraction) saç ekimi, günümüzün en gelişmiş ve güvenilir saç ekimi yöntemidir. Donör bölgeden tek tek alınan saç follikülleri, mikromotor yardımıyla alıcı bölgeye yerleştirilir. Bu yöntem minimal invaziv olup, doğal sonuçlar verir.',
    'services.fue.title.results': '6-12 ay',
    'services.fue.title.advantage1.title': 'İz Bırakmaz',
    'services.fue.title.advantage1.desc': 'Klasik yöntemlerin aksine lineer iz bırakmaz',
    'services.fue.title.advantage2.title': 'Hızlı İyileşme',
    'services.fue.title.advantage2.desc': '7-10 günde tam iyileşme sağlanır',
    'services.fue.title.advantage3.title': 'Doğal Sonuç',
    'services.fue.title.advantage3.desc': 'Kendi saçınızmış gibi doğal görünüm',
    'services.fue.title.advantage4.title': 'Kalıcı Çözüm',
    'services.fue.title.advantage4.desc': 'Yaşam boyu kalıcı sonuçlar',
    'services.fue.title.process1.title': 'Hazırlık',
    'services.fue.title.process1.desc': 'Donör bölge hazırlanır ve folliküller çıkarıma hazır hale getirilir',
    'services.fue.title.process2.title': 'Ekstraksiyon',
    'services.fue.title.process2.desc': 'Mikromotor ile tek tek folliküller çıkarılır',
    'services.fue.title.process3.title': 'İmplantasyon',
    'services.fue.title.process3.desc': 'Folliküller alıcı bölgeye doğal açılarla yerleştirilir',
    'services.fue.title.suitable1': 'Saç dökülmesi yaşayan erkekler',
    'services.fue.title.suitable2': 'Saçları incelen kadınlar',
    'services.fue.title.suitable3': 'Yeterli donör saçı olan kişiler',
    'services.fue.title.suitable4': '18-70 yaş arası bireyler',
    
    // DHI Hair Transplant Details
    'services.dhi.title.tagline': 'Kanal Açmadan Direkt Ekim',
    'services.dhi.title.fullDesc': 'DHI (Direct Hair Implantation) tekniği, saç folliküllerinin özel kalem (implanter pen) ile direkt olarak ekildiği gelişmiş bir yöntemdir. Kanal açma aşaması olmadan tek seferde ekim yapılır, bu da daha hızlı iyileşme sağlar.',
    'services.dhi.title.results': '6-12 ay',
    'services.dhi.title.advantage1.title': 'Kanal Açmadan Ekim',
    'services.dhi.title.advantage1.desc': 'DHI pen ile direkt ekim yapılır',
    'services.dhi.title.advantage2.title': 'Daha Az Travma',
    'services.dhi.title.advantage2.desc': 'Dokuda minimum hasar oluşturur',
    'services.dhi.title.advantage3.title': 'Yoğun Ekim',
    'services.dhi.title.advantage3.desc': 'Daha sık aralıklarla ekim imkanı',
    'services.dhi.title.advantage4.title': 'Kontrollü Açı',
    'services.dhi.title.advantage4.desc': 'Saç çıkış açısının tam kontrolü',
    'services.dhi.title.process1.title': 'Follikül Hazırlığı',
    'services.dhi.title.process1.desc': 'Donör bölgeden folliküller çıkarılır ve hazırlanır',
    'services.dhi.title.process2.title': 'DHI Pen Yükleme',
    'services.dhi.title.process2.desc': 'Folliküller özel DHI kalemlerine yüklenir',
    'services.dhi.title.process3.title': 'Direkt Ekim',
    'services.dhi.title.process3.desc': 'Tek hareketle hem kanal açılır hem de ekim yapılır',
    'services.dhi.title.suitable1': 'Yoğun saç çizgisi isteyenler',
    'services.dhi.title.suitable2': 'Mevcut saçları arasına ekim yapılacaklar',
    'services.dhi.title.suitable3': 'Hassas derili bireyler',
    'services.dhi.title.suitable4': 'Hızlı iyileşme isteyenler',
    
    // Hybrid FUE+DHI Details
    'services.hybrid.title.tagline': 'İki Tekniğin Mükemmel Birleşimi',
    'services.hybrid.title.fullDesc': 'Hybrid FUE+DHI tekniği, FUE ve DHI yöntemlerinin avantajlarını birleştiren en gelişmiş saç ekimi yöntemidir. Donör bölgeden FUE ile alınan folliküller, DHI tekniği ile ekilir. Bu sayede hem maximum graft sayısı hem de optimal yoğunluk elde edilir.',
    'services.hybrid.title.results': '6-12 ay',
    'services.hybrid.title.advantage1.title': 'Maksimum Graft',
    'services.hybrid.title.advantage1.desc': 'En fazla follikül sayısı alınabilir',
    'services.hybrid.title.advantage2.title': 'Optimal Yoğunluk',
    'services.hybrid.title.advantage2.desc': 'DHI ile yoğun ekim sağlanır',
    'services.hybrid.title.advantage3.title': 'Çifte Avantaj',
    'services.hybrid.title.advantage3.desc': 'İki tekniğin avantajları birleşir',
    'services.hybrid.title.advantage4.title': 'En İyi Sonuç',
    'services.hybrid.title.advantage4.desc': '%99 başarı oranı ile kanıtlanmış',
    'services.hybrid.title.process1.title': 'FUE Ekstraksiyon',
    'services.hybrid.title.process1.desc': 'Donör bölgeden maksimum follikül çıkarılır',
    'services.hybrid.title.process2.title': 'Follikül Ayrıştırma',
    'services.hybrid.title.process2.desc': 'Folliküller bölgelere göre ayrıştırılır',
    'services.hybrid.title.process3.title': 'DHI İmplantasyon',
    'services.hybrid.title.process3.desc': 'DHI tekniği ile yoğun ekim yapılır',
    'services.hybrid.title.suitable1': 'Geniş saç kaybı olan bireyler',
    'services.hybrid.title.suitable2': 'Maximum yoğunluk isteyenler',
    'services.hybrid.title.suitable3': 'En iyi sonucu arayanlar',
    'services.hybrid.title.suitable4': 'Tek seansta çözüm isteyenler',
    
    // Beard Transplant Details
    'services.beard.title.tagline': 'Erkeksi ve Dolgun Sakal',
    'services.beard.title.fullDesc': 'Sakal ekimi, erkeklerde yoğun ve dolgun sakal elde etmek için uygulanan estetik bir işlemdir. Genellikle ense bölgesinden alınan saç follikülleri, sakal bölgesine doğal açılar gözetilerek ekilir. Modern tekniklerle doğal görünüm sağlanır.',
    'services.beard.title.results': '6-12 ay',
    'services.beard.title.advantage1.title': 'Doğal Sakal Çizgisi',
    'services.beard.title.advantage1.desc': 'Yüz yapısına uygun sakal tasarımı',
    'services.beard.title.advantage2.title': 'Yoğun Görünüm',
    'services.beard.title.advantage2.desc': 'Seyrek alanların doldurulması',
    'services.beard.title.advantage3.title': 'Kalıcı Sonuç',
    'services.beard.title.advantage3.desc': 'Yaşam boyu kalıcı sakal',
    'services.beard.title.advantage4.title': 'Erkeksi Görünüm',
    'services.beard.title.advantage4.desc': 'Maskülen ve çekici görünüm',
    'services.beard.title.process1.title': 'Tasarım',
    'services.beard.title.process1.desc': 'Yüz yapısına uygun sakal çizgisi çizilir',
    'services.beard.title.process2.title': 'Follikül Alımı',
    'services.beard.title.process2.desc': 'Donör bölgeden uygun folliküller seçilir',
    'services.beard.title.process3.title': 'Ekim İşlemi',
    'services.beard.title.process3.desc': 'Sakal bölgesine doğal açılarla ekim yapılır',
    'services.beard.title.suitable1': 'Sakalı olmayan erkekler',
    'services.beard.title.suitable2': 'Seyrek sakallı bireyler',
    'services.beard.title.suitable3': 'Sakal şekli düzeltmek isteyenler',
    'services.beard.title.suitable4': '18-70 yaş arası erkekler',
    
    // Eyebrow Transplant Details
    'services.eyebrow.title.tagline': 'Doğal ve Şekilli Kaşlar',
    'services.eyebrow.title.fullDesc': 'Kaş ekimi, kaş bölgesindeki seyreklik veya kayıpların giderilmesi için uygulanan estetik işlemdir. Genellikle ense bölgesinden alınan tek saç telleri, kaş bölgesine doğal büyüme yönünde ekilir. Yüz ifadesini güçlendirir.',
    'services.eyebrow.title.results': '6-12 ay',
    'services.eyebrow.title.advantage1.title': 'Doğal Kaş Şekli',
    'services.eyebrow.title.advantage1.desc': 'Yüz yapısına uygun kaş tasarımı',
    'services.eyebrow.title.advantage2.title': 'Kalıcı Çözüm',
    'services.eyebrow.title.advantage2.desc': 'Makyaj ihtiyacını ortadan kaldırır',
    'services.eyebrow.title.advantage3.title': 'Doğal Görünüm',
    'services.eyebrow.title.advantage3.desc': 'Gerçek kaş teli gibi sonuç',
    'services.eyebrow.title.advantage4.title': 'Güçlü İfade',
    'services.eyebrow.title.advantage4.desc': 'Yüz ifadesini belirginleştirir',
    'services.eyebrow.title.process1.title': 'Kaş Tasarımı',
    'services.eyebrow.title.process1.desc': 'Altın oran kurallarına göre kaş şekli belirlenir',
    'services.eyebrow.title.process2.title': 'Follikül Seçimi',
    'services.eyebrow.title.process2.desc': 'En ince ve uygun folliküller seçilir',
    'services.eyebrow.title.process3.title': 'Hassas Ekim',
    'services.eyebrow.title.process3.desc': 'Doğal kaş yönünde hassas ekim yapılır',
    'services.eyebrow.title.suitable1': 'Kaşları olmayan kadınlar',
    'services.eyebrow.title.suitable2': 'Seyrek kaşlı bireyler',
    'services.eyebrow.title.suitable3': 'Kaş şeklini düzeltmek isteyenler',
    'services.eyebrow.title.suitable4': '18-70 yaş arası kadın ve erkekler',
    
    // Stem Cell Treatment Details
    'services.stemCell.title.tagline': 'Yenileyici Kök Hücre Terapisi',
    'services.stemCell.title.fullDesc': 'Kök hücre tedavisi, saç folliküllerinin rejenerasyonunu destekleyen yenilikçi bir tedavi yöntemidir. Hastanın kendi yağ dokusundan elde edilen kök hücreler, saç derisi altına enjekte edilerek mevcut saçların güçlenmesini ve yeni saç tellerinin oluşumunu destekler.',
    'services.stemCell.title.results': '6-12 ay',
    'services.stemCell.title.advantage1.title': 'Doğal Rejenerasyon',
    'services.stemCell.title.advantage1.desc': 'Kendi kök hücrelerinizle tedavi',
    'services.stemCell.title.advantage2.title': 'Güçlü Folliküller',
    'services.stemCell.title.advantage2.desc': 'Mevcut saçların güçlenmesi',
    'services.stemCell.title.advantage3.title': 'Yeni Saç Büyümesi',
    'services.stemCell.title.advantage3.desc': 'Yeni folliküllerin oluşumunu destekler',
    'services.stemCell.title.advantage4.title': 'Güvenli Tedavi',
    'services.stemCell.title.advantage4.desc': 'Kendi dokularınızdan elde edilen',
    'services.stemCell.title.process1.title': 'Yağ Dokusu Alımı',
    'services.stemCell.title.process1.desc': 'Karın bölgesinden minimal yağ alınır',
    'services.stemCell.title.process2.title': 'Kök Hücre İzolasyonu',
    'services.stemCell.title.process2.desc': 'Özel laboratuvarda kök hücreler ayrıştırılır',
    'services.stemCell.title.process3.title': 'Enjeksiyon',
    'services.stemCell.title.process3.desc': 'Saç derisine kök hücre enjeksiyonu yapılır',
    'services.stemCell.title.suitable1': 'Saç kaybının başladığı dönemdeki bireyler',
    'services.stemCell.title.suitable2': 'Saç kalitesini artırmak isteyenler',
    'services.stemCell.title.suitable3': 'Doğal tedavi arayanlar',
    'services.stemCell.title.suitable4': 'Saç ekimi sonrası destekleyici tedavi isteyenler',
    
    // Exosome Treatment Details
    'services.exosome.title.tagline': 'Gelecekteki Saç Rejenerasyonu',
    'services.exosome.title.fullDesc': 'Eksozom tedavisi, regeneratif tıbbın en yeni ve etkili yöntemlerinden biridir. Eksozomlar, hücreler arası iletişimi sağlayan mikroskobik parçacıklardır. Saç derisine uygulanan eksozomlar, hasar görmüş follikülleri onarır ve yeni saç büyümesini tetikler.',
    'services.exosome.title.results': '3-8 ay',
    'services.exosome.title.advantage1.title': 'En Yeni Teknoloji',
    'services.exosome.title.advantage1.desc': 'Regeneratif tıbbın son buluşu',
    'services.exosome.title.advantage2.title': 'Hızlı Sonuç',
    'services.exosome.title.advantage2.desc': '3-4 ayda görünür sonuçlar',
    'services.exosome.title.advantage3.title': 'Minimal İnvaziv',
    'services.exosome.title.advantage3.desc': 'Sadece enjeksiyon ile uygulama',
    'services.exosome.title.advantage4.title': 'Güçlü Etkili',
    'services.exosome.title.advantage4.desc': 'Hücresel düzeyde rejenerasyon',
    'services.exosome.title.process1.title': 'Hazırlık',
    'services.exosome.title.process1.desc': 'Saç derisi temizlenir ve hazırlanır',
    'services.exosome.title.process2.title': 'Eksozom Uygulaması',
    'services.exosome.title.process2.desc': 'Özel eksozom serumu saç derisine enjekte edilir',
    'services.exosome.title.process3.title': 'Takip',
    'services.exosome.title.process3.desc': 'Düzenli kontroller ile süreç takip edilir',
    'services.exosome.title.suitable1': 'Erken evre saç kaybı yaşayanlar',
    'services.exosome.title.suitable2': 'Hızlı sonuç isteyenler',
    'services.exosome.title.suitable3': 'İnvaziv işlem istemeyen bireyler',
    'services.exosome.title.suitable4': 'Saç kalitesini artırmak isteyenler',
    
    // Mesotherapy Details
    'services.mesotherapy.title.tagline': 'Vitamin ve Mineral Desteği',
    'services.mesotherapy.title.fullDesc': 'Saç mezoterapisi, saç derisine özel vitamin, mineral ve besin maddeleri karışımının mikroenjeksiyon yöntemi ile verildiği tedavi yöntemidir. Saç folliküllerinin beslenmesini artırarak saç kalitesini iyileştirir ve saç dökülmesini azaltır.',
    'services.mesotherapy.title.results': '2-6 ay',
    'services.mesotherapy.title.advantage1.title': 'Beslenme Desteği',
    'services.mesotherapy.title.advantage1.desc': 'Folliküllere direkt besin takviyesi',
    'services.mesotherapy.title.advantage2.title': 'Dökülme Azaltır',
    'services.mesotherapy.title.advantage2.desc': 'Saç dökülmesini önemli ölçüde azaltır',
    'services.mesotherapy.title.advantage3.title': 'Saç Kalitesi',
    'services.mesotherapy.title.advantage3.desc': 'Mevcut saçların kalınlaşması',
    'services.mesotherapy.title.advantage4.title': 'Pratik Uygulama',
    'services.mesotherapy.title.advantage4.desc': '20-30 dakikada tamamlanır',
    'services.mesotherapy.title.process1.title': 'Analiz',
    'services.mesotherapy.title.process1.desc': 'Saç derisi ve saç analizi yapılır',
    'services.mesotherapy.title.process2.title': 'Karışım Hazırlığı',
    'services.mesotherapy.title.process2.desc': 'Kişiye özel vitamin karışımı hazırlanır',
    'services.mesotherapy.title.process3.title': 'Mikroenjeksiyon',
    'services.mesotherapy.title.process3.desc': 'Saç derisine hassas enjeksiyon yapılır',
    'services.mesotherapy.title.suitable1': 'Saç dökülmesi yaşayan bireyler',
    'services.mesotherapy.title.suitable2': 'Saç kalitesini artırmak isteyenler',
    'services.mesotherapy.title.suitable3': 'Destekleyici tedavi arayanlar',
    'services.mesotherapy.title.suitable4': 'Pratik çözüm isteyenler',
    
    // PRP Treatment Details
    'services.prp.title.tagline': 'Doğal İyileştirici Güç',
    'services.prp.title.fullDesc': 'PRP (Platelet Rich Plasma) tedavisi, hastanın kendi kanından elde edilen trombositten zengin plazmanın saç derisine enjekte edildiği doğal bir tedavi yöntemidir. Trombositler büyüme faktörleri salgılayarak saç folliküllerinin yenilenmesini ve güçlenmesini sağlar.',
    'services.prp.title.results': '4-8 ay',
    'services.prp.title.advantage1.title': 'Doğal Tedavi',
    'services.prp.title.advantage1.desc': 'Kendi kanınızdan elde edilen',
    'services.prp.title.advantage2.title': 'Büyüme Faktörleri',
    'services.prp.title.advantage2.desc': 'Doğal büyüme faktörleri salınımı',
    'services.prp.title.advantage3.title': 'Güvenli Yöntem',
    'services.prp.title.advantage3.desc': 'Yan etkisi minimal tedavi',
    'services.prp.title.advantage4.title': 'Etkili Sonuçlar',
    'services.prp.title.advantage4.desc': 'Kanıtlanmış başarı oranı',
    'services.prp.title.process1.title': 'Kan Alımı',
    'services.prp.title.process1.desc': 'Hastadan 10-20 cc kan alınır',
    'services.prp.title.process2.title': 'Santrifüj',
    'services.prp.title.process2.desc': 'Kan özel cihazda ayrıştırılır',
    'services.prp.title.process3.title': 'PRP Enjeksiyonu',
    'services.prp.title.process3.desc': 'Elde edilen PRP saç derisine enjekte edilir',
    'services.prp.title.suitable1': 'Saç incelmesi yaşayan bireyler',
    'services.prp.title.suitable2': 'Doğal tedavi arayanlar',
    'services.prp.title.suitable3': 'Saç ekimi sonrası destekleyici tedavi isteyenler',
    'services.prp.title.suitable4': 'Güvenli yöntem tercih edenler',
    
    // Contact Page
    'contact.title': 'İletişim',
    'contact.subtitle': 'Size nasıl yardımcı olabileceğimizi öğrenmek için bizimle iletişime geçin. Uzman ekibimiz tüm sorularınızı yanıtlamaya hazır.',
    'contact.callNow': 'Hemen Ara',
    'contact.whatsapp': 'WhatsApp',
    'contact.form.title': 'Ücretsiz Muayene',
    'contact.form.subtitle': 'Formu doldurun, size en kısa sürede dönüş yapalım',
    'contact.form.name': 'Adınız Soyadınız *',
    'contact.form.surname': 'Soyadınız',
    'contact.form.namePlaceholder': 'Adınız ve soyadınız',
    'contact.form.phone': 'Telefon Numaranız *',
    'contact.form.phonePlaceholder': '+90 5XX XXX XX XX',
    'contact.form.email': 'E-posta Adresiniz *',
    'contact.form.emailPlaceholder': 'ornek@email.com',
    'contact.form.message': 'Mesajınız',
    'contact.form.messagePlaceholder': 'Hangi konuda bilgi almak istiyorsunuz?',
    'contact.form.submit': 'Mesaj Gönder',
    'contact.form.sending': 'Gönderiliyor...',
    'contact.form.optional': 'Opsiyonel',
    'contact.info.title': 'İletişim Bilgileri',
    'contact.info.subtitle': 'Merkezi konumumuzda modern kliniğimizde size hizmet veriyoruz. Randevu almak veya sorularınızı iletmek için aşağıdaki yollardan bize ulaşabilirsiniz.',
    'contact.info.address': 'Adres',
    'contact.info.phone': 'Telefon',
    'contact.info.email': 'E-posta',
    'contact.info.hours': 'Çalışma Saatleri',
    'contact.info.phone.title': 'Telefon',
    'contact.info.email.title': 'E-posta',
    'contact.info.address.title': 'Adres',
    'contact.info.whatsapp.title': 'WhatsApp',
    'contact.info.addressLine1': 'İstanbul/Ataşehir',
    'contact.info.addressLine2': '',
    'contact.info.phoneNumber': '+90 543 176 7634',
    'contact.info.workingHours': 'Pazartesi - Cumartesi: 09:00 - 18:00',
    'contact.info.sunday': 'Pazar: Kapalı',
    'contact.info.email1': 'info@vesnahairclinic.com',
    'contact.info.email2': 'support@vesnahairclinic.com',
    'contact.location.title': 'Konum',
    'contact.location.viewOnMap': 'Haritada Görüntüle',
    'contact.social.title': 'Sosyal Medya',
    'contact.cta.title': 'Size Nasıl Yardımcı Olabiliriz?',
    'contact.cta.subtitle': 'Uzman ekibimizle iletişime geçin ve hayalinizdeki saçlara kavuşun',
    'contact.why.title': 'Neden Vesna Hair Clinic?',
    'contact.why.experience': 'Deneyimli Ekip',
    'contact.why.experienceDesc': '8+ yıl deneyim ve binlerce başarılı operasyon',
    'contact.why.guarantee': 'Garantili Sonuçlar',
    'contact.why.guaranteeDesc': '%98 başarı oranı ile kanıtlanmış kalite',
    'contact.why.support': '7/24 Destek',
    'contact.why.supportDesc': 'Tedavi öncesi ve sonrası tam destek',
    'contact.success.title': 'Mesajınız Başarıyla Gönderildi! 🎉',
    'contact.success.subtitle': 'Talebiniz alınmıştır. Uzman ekibimiz en kısa sürede sizinle iletişime geçecektir.',
    'contact.success.note': 'Genellikle 24 saat içinde yanıt veriyoruz.',
    'contact.success.callNow': 'Hemen Ara',
    'contact.success.whatsapp': 'WhatsApp',
    'contact.success.close': 'Kapat',
    'contact.badge': 'İletişim',
    'contact.mainTitle': 'ILETISIME GECIN',
    'contact.mainSubtitle': 'Uzman ekibimizle iletişime geçin ve hayalinizdeki saçlara kavuşun',
    'contact.infoTitle': 'İletişim Bilgileri',
    'contact.infoSubtitle': 'Size en uygun iletişim kanalından ulaşabilirsiniz',
    'contact.formTitle': 'Mesaj Gönderin',
    'contact.formSubtitle': 'Ücretsiz konsültasyon için bizimle iletişime geçin',
    'contact.quickCall': 'Hemen Ara',
    'contact.quickWhatsapp': 'WhatsApp',
    'contact.quickMessage': 'Anlık mesaj',
    
    // About Page
    'about.title': 'Hakkımızda',
    'about.description': 'Vesna Hair Clinic, saç ekimi alanında yılların deneyimi ve bilimsel yaklaşımın birleşimiyle kurulmuş bir sağlık kuruluşudur.',
    'about.paragraph1': 'Vesna Hair Clinic, saç ekimi alanında yılların deneyimi ve bilimsel yaklaşımın birleşimiyle kurulmuş bir sağlık kuruluşudur. Kurucularımız, sektörün önde gelen kurumsal kliniklerinde çalışmış ve binlerce başarılı operasyonun sorumluluğunu üstlenmiş deneyimli uzmanlardır.',
    'about.paragraph2': 'Klinik olarak hedefimiz, her hastaya kişiselleştirilmiş çözümler sunarak, en güncel teknolojiler ve etik ilkeler doğrultusunda doğal ve kalıcı sonuçlar sağlamaktır. Vesna Hair Clinic\'te tüm süreçler hasta memnuniyeti, hijyen standartları ve profesyonellik temelinde yürütülmektedir.',
    'about.paragraph3': 'Her biri kendi alanında yetkin sağlık personelimizle birlikte, sadece estetik değil aynı zamanda güven veren bir tedavi süreci sunmayı hedefliyoruz. Vesna Hair Clinic, kalite, şeffaflık ve sürdürülebilir başarı temelli modern bir saç ekimi kliniğidir.',
    'about.whyUs': 'Neden Vesna Hair Clinic?',
    'about.whyUsDesc': 'Kalite, güven ve başarı odaklı yaklaşımımızla fark yaratıyoruz',
    'about.feature1.title': 'Deneyimli Kadro',
    'about.feature1.desc': 'Sektörün önde gelen kliniklerinde çalışmış uzman doktorlar',
    'about.feature2.title': 'Binlerce Başarılı Operasyon',
    'about.feature2.desc': 'Yıllar içinde gerçekleştirilen binlerce başarılı müdahale',
    'about.feature3.title': 'Hasta Memnuniyeti',
    'about.feature3.desc': 'Kişiselleştirilmiş çözümler ve güven veren tedavi süreci',
    'about.feature4.title': 'Güncel Teknoloji',
    'about.feature4.desc': 'En güncel teknolojiler ve etik ilkeler doğrultusunda hizmet',
    'about.mission': 'Misyonumuz',
    'about.missionDesc': 'Saç sağlığı alanında en kaliteli hizmeti sunarak, müşterilerimizin kendine güvenini artırmak ve hayat kalitelerini yükseltmek. Her hastaya kişiselleştirilmiş çözümler sunarak doğal ve kalıcı sonuçlar elde etmeyi hedefliyoruz.',
    'about.vision': 'Vizyonumuz',
    'about.visionDesc': 'Türkiye\'nin en güvenilir saç kliniği olarak, uluslararası standartlarda hizmet sunan öncü bir kuruluş olmak. Sürekli gelişim ve yenilik anlayışımızla sektördeki lider konumumuzu korumak istiyoruz.',
    'about.stats.operations': 'Başarılı Operasyon',
    'about.stats.experience': 'Yıl Deneyim',
    'about.stats.satisfaction': 'Müşteri Memnuniyeti',
    'about.stats.success': 'Başarı Oranı',
    'about.stats.support': 'Destek Hizmeti',
    'about.cta.title': 'Hayalinizdeki Saçlara Kavuşun',
    'about.cta.subtitle': 'Uzman ekibimizden ücretsiz konsültasyon alın ve size en uygun tedavi planını keşfedin',
    'about.mission.title': 'Misyonumuz',
    'about.mission.description': 'Saç sağlığı alanında en kaliteli hizmeti sunarak, müşterilerimizin kendine güvenini artırmak ve hayat kalitelerini yükseltmek misyonumuz.',
    'about.vision.title': 'Vizyonumuz',
    'about.vision.description': 'Türkiye\'nin en güvenilir saç kliniği olarak, uluslararası standartlarda hizmet sunan öncü bir kuruluş olmak vizyonumuz.',
    
    // Before After Page
    'beforeAfter.title': 'Önce / Sonra',
    'beforeAfter.subtitle': 'Başarılı saç ekimi sonuçlarımızı inceleyin ve değişimin gücünü görün',
    'beforeAfter.before': 'ÖNCE',
    'beforeAfter.after': 'SONRA',
    'beforeAfter.heroSubtitle': 'Başarılı Sonuçlarımız',
    'beforeAfter.heroDescription': '',
    'beforeAfter.heroDescriptionHighlight': '',
    'beforeAfter.realResults': 'Gerçek Sonuçlar',
    'beforeAfter.realResultsDesc': '',
    'beforeAfter.ctaTitle1': 'Hayalinizdeki Saçlara',
    'beforeAfter.ctaTitle2': 'Bugün Başlayın',
    'beforeAfter.ctaSubtitle': 'Uzman ekibimizle ücretsiz konsültasyonunuzu alın ve',
    'beforeAfter.ctaSubtitleHighlight': 'kendi başarı hikayenizi yazmaya başlayın.',
    'beforeAfter.nextYou': 'Sıradaki Siz Olun',
    'beforeAfter.callNow': 'Hemen Ara',
    'beforeAfter.whatsapp': 'WhatsApp',
    'beforeAfter.stat1': 'Mutlu Hasta',
    'beforeAfter.stat2': 'Memnuniyet',
    'beforeAfter.stat3': 'Yıl Tecrübe',
    'beforeAfter.stat4': 'Destek',
    'beforeAfter.trust1': '3800+ Mutlu Hasta',
    'beforeAfter.trust1Desc': 'Başarılı operasyonlar',
    'beforeAfter.trust2': '%98 Başarı Oranı',
    'beforeAfter.trust2Desc': 'Kanıtlanmış kalite',
    'beforeAfter.trust3': '7/24 Destek',
    'beforeAfter.trust3Desc': 'Sürekli hizmet',
    'beforeAfter.result1': 'Muhteşem Dönüşüm',
    'beforeAfter.result2': 'Doğal Sonuçlar',
    'beforeAfter.result3': 'Hayal Kurduğu Saçlar',
    'beforeAfter.result4': 'Mükemmel Sonuç',
    'beforeAfter.result5': 'Yoğun ve Doğal',
    'beforeAfter.result6': 'Etkileyici Değişim',
    'beforeAfter.result7': 'Kusursuz Çizgi',
    'beforeAfter.result8': 'Genç ve Dinamik',
    'beforeAfter.result9': 'Tam İstediği Gibi',
    'beforeAfter.satisfied': 'memnun',
    
    // Common
    'common.getInfo': 'Bilgi Al',
    'common.freeConsultation': 'Ücretsiz Muayene',
    'common.appointment': 'Randevu Al',
    'common.settings': 'Ayarlar',
    'common.loading': 'Yükleniyor...',
    'common.sending': 'Gönderiliyor...',
    'common.send': 'Gönder',
    'common.before': 'ÖNCE',
    'common.after': 'SONRA',
    'common.hairTransplantResults': 'Saç Ekimi Sonuçları',
    'common.hours': 'saat',
    'common.minutes': 'dakika',
    
    // Footer
    'footer.description': 'Hayalinizdeki saçlara birlikte ulaşalım. Ekibimiz tüm sorularınızı yanıtlamaya ve daha dolgun, doğal görünümlü saçlara giden yolculuğunuzda size eşlik etmeye hazır.',
    'footer.quickLinks': 'Hızlı Bağlantılar',
    'footer.contact': 'İletişim',
    'footer.certificate': 'Sağlık Sertifikası',
    'footer.rights': 'Tüm hakları saklıdır.',
    'footer.about': 'Hakkımızda',
    'footer.address': 'Adres',
    'footer.workingHours': 'Çalışma Saatleri',
    'footer.newsletter': 'Bülten',
    'footer.newsletterDesc': 'Yeniliklerden haberdar olun',
    'footer.emailPlaceholder': 'E-posta adresiniz',
    'footer.subscribe': 'Abone Ol',
    'footer.privacy': 'Gizlilik Politikası',
    'footer.terms': 'Kullanım Şartları',
    
    // WhatsApp
    'whatsapp.contact': 'WhatsApp ile İletişim',
    
    // FAQ Section (Services Page)
    'faq.title': 'Merak Edilenler',
    'faq.subtitle': 'Saç ekimi hakkında en çok sorulan sorular ve cevapları',
    'faq.question1': 'Saç ekimi acılı bir işlem mi?',
    'faq.answer1': 'Lokal anestezi ile yapılan saç ekimi işlemi tamamen ağrısızdır. Sadece anestezi sırasında hafif bir rahatsızlık hissedilir.',
    'faq.question2': 'Sonuçları ne zaman görebilirim?',
    'faq.answer2': 'İlk sonuçlar 6-8 ay sonra görülmeye başlar. Tam sonuçlar 12-18 ay içinde ortaya çıkar.',
    'faq.question3': 'İyileşme süreci nasıl?',
    'faq.answer3': 'İlk 3 gün dinlenme önerilir. 7-10 gün içinde kabuklar dökülerek iyileşme tamamlanır.',
    'faq.question4': 'Kalıcı mı yoksa tekrar dökülür mü?',
    'faq.answer4': 'Ense bölgesinden alınan saçlar genetik olarak dökülmeye dirençlidir ve kalıcıdır.',
    'faq.question5': 'Yaş sınırı var mı?',
    'faq.answer5': '18 yaş üstü herkes için uygundur. Kesin sonuç için muayene önerilir.',
    'faq.question6': 'Fiyatlar nasıl belirleniyor?',
    'faq.answer6': 'Kullanılacak tekniğe ve kişiye özel planlama doğrultusunda belirlenir.',

    // Instagram Section (Contact Page)
    'instagram.title': 'Instagram\'da Bizi Takip Edin',
    'instagram.subtitle': 'En son haberler, hasta hikayeleri ve klinik güncellemelerimiz için Instagram\'da bizi takip edin',
    'instagram.description': 'En son saç ekimi sonuçlarımız, hasta hikayelerimiz ve klinik güncellemelerimiz için Instagram\'da bizi takip edin! ✨',
    'instagram.followButton': 'Instagram\'da Takip Et',
    'instagram.postNumber': 'Post #',
    'instagram.loading': 'Postlar yükleniyor...',
    'instagram.postAlt': 'Instagram gönderisi',
    'common.reels': 'REELS',
    'common.viewPost': 'Görüntüle',
    
    
    // 404 Page
    '404.title': 'Sayfa Bulunamadı',
    '404.description': 'Aradığınız sayfa taşınmış, silinmiş veya geçici olarak kullanılamıyor olabilir.',
    '404.backHome': 'Ana Sayfaya Dön',
    '404.contact': 'İletişim',
    '404.needHelp': 'Yardıma mı İhtiyacınız Var?',
    '404.popularLinks': 'Popüler Bağlantılar',
    '404.searchPlaceholder': 'Aradığınız sayfayı yazın...',
    '404.helpTitle': 'Yardıma mı İhtiyacınız Var?',
    '404.helpDescription': 'Size hemen yardımcı olalım',
    '404.phone': 'Telefon',
    '404.instantMessage': 'Anında Mesaj',
    '404.tip': '💡 İpucu: Arama kutusuna "hakkımızda", "hizmetler" veya "iletişim" yazarak doğrudan sayfalara gidebilirsiniz',
    
    // Security Warnings
    'security.devToolsBlocked': '⚠️ F12 Developer Tools açılması yasaktır!',
    'security.consoleBlocked': '⚠️ Console kapatılmıştır!',
    'security.viewSourceBlocked': '⚠️ Sayfa kaynağı kapatılmıştır!',
    'security.saveBlocked': '⚠️ Sayfa kaydetme kapatılmıştır!',
    'security.selectAllBlocked': '⚠️ Tümünü seç kapatılmıştır!',
    'security.copyBlocked': '⚠️ Kopyalama kapatılmıştır!',
    'security.cutBlocked': '⚠️ Kesme kapatılmıştır!',
    'security.contextMenuBlocked': '⚠️ Sağ tık menüsü kapatılmıştır!',
    'security.dragDropBlocked': '⚠️ Sürükle & bırak kapatılmıştır!',
    'security.devToolsDetected': '⚠️ Developer Tools algılandı! Lütfen kapatın!',
    'security.consoleStop': 'DUR! 🛑',
    'security.consoleFeature': 'Bu bir tarayıcı özelliğidir ve geliştiriciler için tasarlanmıştır.',
    'security.consoleScam': 'Birisi size buraya kod yapıştırmanızı söylüyorsa, bu bir dolandırıcılık girişimidir.',
    'security.consoleClinic': 'Vesna Hair Clinic - Güvenliğiniz bizim için önemlidir! 🔒'
  },
  
  en: {
    // Header
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.beforeAfter': 'Before/After',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.badge': 'Turkey\'s Most Trusted Hair Clinic',
    'hero.title': 'Achieve Your',
    'hero.titleHighlight': 'Dream Hair',
    'hero.subtitle': 'Natural, permanent results with professional hair transplant and hair care services. Let\'s achieve your dream hair together.',
    'hero.consultation': 'Free Consultation',
    'hero.gallery': 'View Gallery',
    'hero.cta.consultation': 'Free Consultation',
    'hero.cta.whatsapp': 'WhatsApp Contact',
    'hero.stats.customers': '3800+ Happy Patients',
    'hero.stats.customersDesc': 'Successful operations',
    'hero.stats.experience': '8+ Years Experience',
    'hero.stats.experienceDesc': 'Expert team',
    'hero.stats.success': '98% Success Rate',
    'hero.stats.successDesc': 'Quality results',
    
    // Hero Form
    'hero.form.title': 'Free Consultation',
    'hero.form.name': 'Your Name',
    'hero.form.surname': 'Your Surname',
    'hero.form.phone': 'Phone',
    'hero.form.email': 'Email',
    'hero.form.message': 'Your Message (optional)',
    'hero.form.submit': 'Free Consultation',
    
    // Form
    'form.title': 'Free Consultation',
    'form.subtitle': 'Fill out the form for free consultation',
    'form.name': 'Your Name',
    'form.surname': 'Your Surname',
    'form.phone': 'Phone',
    'form.email': 'Email',
    'form.message': 'Your Message (optional)',
    'form.submit': 'Free Consultation',
    'form.sending': 'Sending...',
    'form.success': 'Your message has been sent successfully! We will get back to you as soon as possible.',
    'form.error': 'An error occurred. Please try again.',
    'form.errorPhone': 'An error occurred. Please contact us by phone.',
    'form.securityMessage': '✅ 100% secure • 📞 24h response • 🎯 Personal solution',
    
    // Buttons
    'buttons.getInfo': 'Get Info',
    'buttons.bookAppointment': 'Book Appointment',
    'buttons.infoAndAppointment': 'Info & Appointment',
    'buttons.callNow': 'Call Now',
    'buttons.whatsapp': 'WhatsApp',
    'buttons.learnMore': 'Learn More',
    
    // Stats
    'stats.customers': 'Happy Customers',
    'stats.experience': 'Years Experience',
    'stats.satisfaction': 'Customer Satisfaction',
    'stats.support': 'Support',
    
    // Services Page
    'services.title': 'Our Services',
    'services.subtitle': 'We offer you the best hair transplant services with modern techniques and our experienced team.',
    'services.cta.title': 'Which Treatment is Right for You?',
    'services.cta.subtitle': 'Get a free analysis from our expert doctors',
    'services.expertsTitle': 'Our Expert Services',
    'services.expertsDesc': 'We perform detailed analysis to determine the most suitable treatment method for you',
    'services.process.title': 'Our Treatment Process',
    'services.process.subtitle': 'Step by step professional approach',
    'services.faq.title': 'Frequently Asked Questions',
    'services.faq.subtitle': 'What you wonder',
    'services.fue.title': 'SAPPHIRE FUE Hair Transplant',
    'services.fue.desc': 'Natural hair transplant with Follicular Unit Extraction method',
    'services.dhi.title': 'DHI Hair Transplant',
    'services.dhi.desc': 'Advanced hair transplant with Direct Hair Implantation',
    'services.prp.title': 'PRP Treatment',
    'services.prp.desc': 'Hair strengthening with Platelet Rich Plasma',
    'services.mesotherapy.title': 'Mesotherapy',
    'services.mesotherapy.desc': 'Special vitamin cocktail for scalp',
    'services.beard.title': 'Beard Transplant',
    'services.beard.desc': 'Professional beard and mustache transplant for men',
    'services.eyebrow.title': 'Eyebrow Transplant',
    'services.eyebrow.desc': 'Eyebrow densification and shaping for men and women',
    'services.hybrid.title': 'HYBRID FUE+DHI',
    'services.hybrid.desc': 'Most advanced hair transplant combining FUE and DHI techniques',
    'services.stemCell.title': 'Stem Cell Treatment',
    'services.stemCell.desc': 'Stem cell treatment to strengthen hair follicles',
    'services.exosome.title': 'Exosome',
    'services.exosome.desc': 'Hair regeneration with innovative exosome treatment',
    'services.process.step1.title': 'Transfer\n(Optional)',
    'services.process.step1.desc': 'Airport pick-up and transfer service',
    'services.process.step2.title': 'Consultation',
    'services.process.step2.desc': 'Free examination and analysis',
    'services.process.step3.title': 'Planning',
    'services.process.step3.desc': 'Personalized treatment plan',
    'services.process.step4.title': 'Implementation',
    'services.process.step4.desc': 'Professional hair transplant procedure',
    'services.process.step5.title': 'Hotel (Optional)',
    'services.process.step5.desc': 'Comfortable accommodation facility',
    'services.process.step6.title': 'Follow-up',
    'services.process.step6.desc': 'Continuous support and monitoring',
    'services.faq.question1': 'Is hair transplant painful?',
    'services.faq.question2': 'When will results be visible?',
    'services.faq.question3': 'Is hair transplant permanent?',
    'services.faq.question4': 'Which technique is better?',
    'services.badge': 'Our Services',
    'services.mainTitle1': 'HAIR TRANSPLANT',
    'services.mainTitle2': 'SERVICES',
    'services.mainSubtitle': 'We provide you with the best service with modern technology and our expert team',
    'services.gridTitle': 'Our Service Options',
    'services.gridSubtitle': 'Let\'s determine the most suitable hair transplant method for you together',
    'services.popular': 'Popular',
    'services.duration': 'Duration',
    'services.recovery': 'Recovery',
    'services.success': 'Success',
    'services.details': 'Details',
    'services.processTitle': 'How Does the Process Work?',
    'services.processSubtitle': 'We complete the hair transplant process in 6 steps',
    'services.ctaTitle': 'Achieve Your Dream Hair',
    'services.ctaSubtitle': 'Get a free consultation from our expert team',
    'services.recovery.fue': '7-10 days',
    'services.recovery.dhi': '5-7 days',
    'services.recovery.prp': '1-2 days',
    'services.recovery.mesotherapy': 'None',
    'services.recovery.beard': '5-7 days',
    'services.recovery.eyebrow': '3-5 days',
    'services.recovery.hybrid': '5-10 days',
    'services.recovery.stemCell': '1-3 days',
    'services.recovery.exosome': 'None',
    
    // Modal translations
    'modal.description': 'Description',
    'modal.advantages': 'Advantages',
    'modal.process': 'Treatment Process',
    'modal.suitable': 'Who Is Suitable',
    'modal.idealCandidates': 'Ideal Candidates',
    'modal.results': 'Results',
    
    // FUE Hair Transplant Details
    'services.fue.title.tagline': 'Most Popular and Reliable Method',
    'services.fue.title.fullDesc': 'FUE (Follicular Unit Extraction) hair transplantation is today\'s most advanced and reliable hair transplant method. Hair follicles taken individually from the donor area are placed in the recipient area with the help of a micromotor. This method is minimally invasive and provides natural results.',
    'services.fue.title.results': '6-12 months',
    'services.fue.title.advantage1.title': 'No Scarring',
    'services.fue.title.advantage1.desc': 'Unlike classic methods, leaves no linear scars',
    'services.fue.title.advantage2.title': 'Fast Recovery',
    'services.fue.title.advantage2.desc': 'Complete healing achieved in 7-10 days',
    'services.fue.title.advantage3.title': 'Natural Result',
    'services.fue.title.advantage3.desc': 'Natural appearance as if it were your own hair',
    'services.fue.title.advantage4.title': 'Permanent Solution',
    'services.fue.title.advantage4.desc': 'Lifelong permanent results',
    'services.fue.title.process1.title': 'Preparation',
    'services.fue.title.process1.desc': 'Donor area is prepared and follicles are ready for extraction',
    'services.fue.title.process2.title': 'Extraction',
    'services.fue.title.process2.desc': 'Individual follicles are extracted with micromotor',
    'services.fue.title.process3.title': 'Implantation',
    'services.fue.title.process3.desc': 'Follicles are placed in recipient area at natural angles',
    'services.fue.title.suitable1': 'Men experiencing hair loss',
    'services.fue.title.suitable2': 'Women with thinning hair',
    'services.fue.title.suitable3': 'Individuals with sufficient donor hair',
    'services.fue.title.suitable4': 'Individuals aged 18-70',
    
    // DHI Hair Transplant Details
    'services.dhi.title.tagline': 'Direct Implantation Without Channel Opening',
    'services.dhi.title.fullDesc': 'DHI (Direct Hair Implantation) technique is an advanced method where hair follicles are directly implanted using a special pen (implanter pen). Implantation is done in one step without the channel opening stage, providing faster healing.',
    'services.dhi.title.results': '6-12 months',
    'services.dhi.title.advantage1.title': 'Implantation Without Channel Opening',
    'services.dhi.title.advantage1.desc': 'Direct implantation with DHI pen',
    'services.dhi.title.advantage2.title': 'Less Trauma',
    'services.dhi.title.advantage2.desc': 'Causes minimum damage to tissue',
    'services.dhi.title.advantage3.title': 'Dense Implantation',
    'services.dhi.title.advantage3.desc': 'Possibility of implantation at closer intervals',
    'services.dhi.title.advantage4.title': 'Controlled Angle',
    'services.dhi.title.advantage4.desc': 'Full control of hair exit angle',
    'services.dhi.title.process1.title': 'Follicle Preparation',
    'services.dhi.title.process1.desc': 'Follicles are extracted and prepared from donor area',
    'services.dhi.title.process2.title': 'DHI Pen Loading',
    'services.dhi.title.process2.desc': 'Follicles are loaded into special DHI pens',
    'services.dhi.title.process3.title': 'Direct Implantation',
    'services.dhi.title.process3.desc': 'Both channel opening and implantation in one motion',
    'services.dhi.title.suitable1': 'Those wanting dense hairline',
    'services.dhi.title.suitable2': 'Those needing implantation between existing hair',
    'services.dhi.title.suitable3': 'Individuals with sensitive skin',
    'services.dhi.title.suitable4': 'Those wanting fast recovery',
    
    // Hybrid FUE+DHI Details (English)
    'services.hybrid.title.tagline': 'Perfect Combination of Two Techniques',
    'services.hybrid.title.fullDesc': 'Hybrid FUE+DHI technique is the most advanced hair transplant method that combines the advantages of FUE and DHI methods. Follicles extracted with FUE from the donor area are implanted using DHI technique. This way, both maximum graft count and optimal density are achieved.',
    'services.hybrid.title.results': '6-12 months',
    'services.hybrid.title.advantage1.title': 'Maximum Grafts',
    'services.hybrid.title.advantage1.desc': 'Maximum number of follicles can be extracted',
    'services.hybrid.title.advantage2.title': 'Optimal Density',
    'services.hybrid.title.advantage2.desc': 'Dense implantation with DHI',
    'services.hybrid.title.advantage3.title': 'Double Advantage',
    'services.hybrid.title.advantage3.desc': 'Benefits of both techniques combined',
    'services.hybrid.title.advantage4.title': 'Best Results',
    'services.hybrid.title.advantage4.desc': 'Proven with 99% success rate',
    'services.hybrid.title.process1.title': 'FUE Extraction',
    'services.hybrid.title.process1.desc': 'Maximum follicles extracted from donor area',
    'services.hybrid.title.process2.title': 'Follicle Sorting',
    'services.hybrid.title.process2.desc': 'Follicles sorted according to regions',
    'services.hybrid.title.process3.title': 'DHI Implantation',
    'services.hybrid.title.process3.desc': 'Dense implantation with DHI technique',
    'services.hybrid.title.suitable1': 'Individuals with extensive hair loss',
    'services.hybrid.title.suitable2': 'Those wanting maximum density',
    'services.hybrid.title.suitable3': 'Those seeking the best results',
    'services.hybrid.title.suitable4': 'Those wanting single-session solution',
    
    // Beard Transplant Details (English)
    'services.beard.title.tagline': 'Masculine and Full Beard',
    'services.beard.title.fullDesc': 'Beard transplantation is an aesthetic procedure applied to achieve dense and full beard in men. Hair follicles usually taken from the nape area are implanted in the beard area considering natural angles. Natural appearance is provided with modern techniques.',
    'services.beard.title.results': '6-12 months',
    'services.beard.title.advantage1.title': 'Natural Beard Line',
    'services.beard.title.advantage1.desc': 'Beard design suitable for face structure',
    'services.beard.title.advantage2.title': 'Dense Appearance',
    'services.beard.title.advantage2.desc': 'Filling sparse areas',
    'services.beard.title.advantage3.title': 'Permanent Result',
    'services.beard.title.advantage3.desc': 'Lifelong permanent beard',
    'services.beard.title.advantage4.title': 'Masculine Look',
    'services.beard.title.advantage4.desc': 'Masculine and attractive appearance',
    'services.beard.title.process1.title': 'Design',
    'services.beard.title.process1.desc': 'Beard line drawn suitable for face structure',
    'services.beard.title.process2.title': 'Follicle Extraction',
    'services.beard.title.process2.desc': 'Suitable follicles selected from donor area',
    'services.beard.title.process3.title': 'Implantation',
    'services.beard.title.process3.desc': 'Implantation at natural angles in beard area',
    'services.beard.title.suitable1': 'Men without beard',
    'services.beard.title.suitable2': 'Individuals with sparse beard',
    'services.beard.title.suitable3': 'Those wanting to correct beard shape',
    'services.beard.title.suitable4': 'Men aged 18-70',
    
    // Eyebrow Transplant Details (English)
    'services.eyebrow.title.tagline': 'Natural and Shaped Eyebrows',
    'services.eyebrow.title.fullDesc': 'Eyebrow transplantation is an aesthetic procedure applied to eliminate sparseness or losses in the eyebrow area. Single hair strands usually taken from the nape area are implanted in the eyebrow area in the natural growth direction. Strengthens facial expression.',
    'services.eyebrow.title.results': '6-12 months',
    'services.eyebrow.title.advantage1.title': 'Natural Eyebrow Shape',
    'services.eyebrow.title.advantage1.desc': 'Eyebrow design suitable for face structure',
    'services.eyebrow.title.advantage2.title': 'Permanent Solution',
    'services.eyebrow.title.advantage2.desc': 'Eliminates the need for makeup',
    'services.eyebrow.title.advantage3.title': 'Natural Appearance',
    'services.eyebrow.title.advantage3.desc': 'Result like real eyebrow hair',
    'services.eyebrow.title.advantage4.title': 'Strong Expression',
    'services.eyebrow.title.advantage4.desc': 'Enhances facial expression',
    'services.eyebrow.title.process1.title': 'Eyebrow Design',
    'services.eyebrow.title.process1.desc': 'Eyebrow shape determined according to golden ratio rules',
    'services.eyebrow.title.process2.title': 'Follicle Selection',
    'services.eyebrow.title.process2.desc': 'Finest and most suitable follicles selected',
    'services.eyebrow.title.process3.title': 'Precise Implantation',
    'services.eyebrow.title.process3.desc': 'Precise implantation in natural eyebrow direction',
    'services.eyebrow.title.suitable1': 'Women without eyebrows',
    'services.eyebrow.title.suitable2': 'Individuals with sparse eyebrows',
    'services.eyebrow.title.suitable3': 'Those wanting to correct eyebrow shape',
    'services.eyebrow.title.suitable4': 'Men and women aged 18-70',
    
    // Stem Cell Treatment Details (English)
    'services.stemCell.title.tagline': 'Regenerative Stem Cell Therapy',
    'services.stemCell.title.fullDesc': 'Stem cell treatment is an innovative treatment method that supports the regeneration of hair follicles. Stem cells obtained from the patient\'s own adipose tissue are injected under the scalp to support the strengthening of existing hair and the formation of new hair strands.',
    'services.stemCell.title.results': '6-12 months',
    'services.stemCell.title.advantage1.title': 'Natural Regeneration',
    'services.stemCell.title.advantage1.desc': 'Treatment with your own stem cells',
    'services.stemCell.title.advantage2.title': 'Strong Follicles',
    'services.stemCell.title.advantage2.desc': 'Strengthening of existing hair',
    'services.stemCell.title.advantage3.title': 'New Hair Growth',
    'services.stemCell.title.advantage3.desc': 'Supports formation of new follicles',
    'services.stemCell.title.advantage4.title': 'Safe Treatment',
    'services.stemCell.title.advantage4.desc': 'Obtained from your own tissues',
    'services.stemCell.title.process1.title': 'Adipose Tissue Extraction',
    'services.stemCell.title.process1.desc': 'Minimal fat extracted from abdominal area',
    'services.stemCell.title.process2.title': 'Stem Cell Isolation',
    'services.stemCell.title.process2.desc': 'Stem cells isolated in special laboratory',
    'services.stemCell.title.process3.title': 'Injection',
    'services.stemCell.title.process3.desc': 'Stem cell injection into scalp',
    'services.stemCell.title.suitable1': 'Individuals in early stages of hair loss',
    'services.stemCell.title.suitable2': 'Those wanting to improve hair quality',
    'services.stemCell.title.suitable3': 'Those seeking natural treatment',
    'services.stemCell.title.suitable4': 'Those wanting supportive treatment after hair transplant',
    
    // Exosome Treatment Details (English)
    'services.exosome.title.tagline': 'Future of Hair Regeneration',
    'services.exosome.title.fullDesc': 'Exosome treatment is one of the newest and most effective methods of regenerative medicine. Exosomes are microscopic particles that provide intercellular communication. Exosomes applied to the scalp repair damaged follicles and trigger new hair growth.',
    'services.exosome.title.results': '3-8 months',
    'services.exosome.title.advantage1.title': 'Latest Technology',
    'services.exosome.title.advantage1.desc': 'Latest discovery of regenerative medicine',
    'services.exosome.title.advantage2.title': 'Fast Results',
    'services.exosome.title.advantage2.desc': 'Visible results in 3-4 months',
    'services.exosome.title.advantage3.title': 'Minimally Invasive',
    'services.exosome.title.advantage3.desc': 'Application with injection only',
    'services.exosome.title.advantage4.title': 'Highly Effective',
    'services.exosome.title.advantage4.desc': 'Cellular level regeneration',
    'services.exosome.title.process1.title': 'Preparation',
    'services.exosome.title.process1.desc': 'Scalp cleaned and prepared',
    'services.exosome.title.process2.title': 'Exosome Application',
    'services.exosome.title.process2.desc': 'Special exosome serum injected into scalp',
    'services.exosome.title.process3.title': 'Follow-up',
    'services.exosome.title.process3.desc': 'Process monitored with regular check-ups',
    'services.exosome.title.suitable1': 'Those experiencing early-stage hair loss',
    'services.exosome.title.suitable2': 'Those wanting fast results',
    'services.exosome.title.suitable3': 'Individuals not wanting invasive procedures',
    'services.exosome.title.suitable4': 'Those wanting to improve hair quality',
    
    // Mesotherapy Details (English)
    'services.mesotherapy.title.tagline': 'Vitamin and Mineral Support',
    'services.mesotherapy.title.fullDesc': 'Hair mesotherapy is a treatment method where a special mixture of vitamins, minerals and nutrients is delivered to the scalp through microinjection. It improves hair quality by increasing the nutrition of hair follicles and reduces hair loss.',
    'services.mesotherapy.title.results': '2-6 months',
    'services.mesotherapy.title.advantage1.title': 'Nutritional Support',
    'services.mesotherapy.title.advantage1.desc': 'Direct nutritional supplement to follicles',
    'services.mesotherapy.title.advantage2.title': 'Reduces Hair Loss',
    'services.mesotherapy.title.advantage2.desc': 'Significantly reduces hair loss',
    'services.mesotherapy.title.advantage3.title': 'Hair Quality',
    'services.mesotherapy.title.advantage3.desc': 'Thickening of existing hair',
    'services.mesotherapy.title.advantage4.title': 'Practical Application',
    'services.mesotherapy.title.advantage4.desc': 'Completed in 20-30 minutes',
    'services.mesotherapy.title.process1.title': 'Analysis',
    'services.mesotherapy.title.process1.desc': 'Scalp and hair analysis performed',
    'services.mesotherapy.title.process2.title': 'Mixture Preparation',
    'services.mesotherapy.title.process2.desc': 'Personalized vitamin mixture prepared',
    'services.mesotherapy.title.process3.title': 'Microinjection',
    'services.mesotherapy.title.process3.desc': 'Precise injection into scalp',
    'services.mesotherapy.title.suitable1': 'Individuals experiencing hair loss',
    'services.mesotherapy.title.suitable2': 'Those wanting to improve hair quality',
    'services.mesotherapy.title.suitable3': 'Those seeking supportive treatment',
    'services.mesotherapy.title.suitable4': 'Those wanting practical solutions',
    
    // PRP Treatment Details (English)
    'services.prp.title.tagline': 'Natural Healing Power',
    'services.prp.title.fullDesc': 'PRP (Platelet Rich Plasma) treatment is a natural treatment method where platelet-rich plasma obtained from the patient\'s own blood is injected into the scalp. Platelets release growth factors, enabling renewal and strengthening of hair follicles.',
    'services.prp.title.results': '4-8 months',
    'services.prp.title.advantage1.title': 'Natural Treatment',
    'services.prp.title.advantage1.desc': 'Obtained from your own blood',
    'services.prp.title.advantage2.title': 'Growth Factors',
    'services.prp.title.advantage2.desc': 'Natural growth factor release',
    'services.prp.title.advantage3.title': 'Safe Method',
    'services.prp.title.advantage3.desc': 'Treatment with minimal side effects',
    'services.prp.title.advantage4.title': 'Effective Results',
    'services.prp.title.advantage4.desc': 'Proven success rate',
    'services.prp.title.process1.title': 'Blood Collection',
    'services.prp.title.process1.desc': '10-20 cc blood taken from patient',
    'services.prp.title.process2.title': 'Centrifuge',
    'services.prp.title.process2.desc': 'Blood separated in special device',
    'services.prp.title.process3.title': 'PRP Injection',
    'services.prp.title.process3.desc': 'Obtained PRP injected into scalp',
    'services.prp.title.suitable1': 'Individuals experiencing hair thinning',
    'services.prp.title.suitable2': 'Those seeking natural treatment',
    'services.prp.title.suitable3': 'Those wanting supportive treatment after hair transplant',
    'services.prp.title.suitable4': 'Those preferring safe methods',
    
    // Contact Page
    'contact.title': 'Contact',
    'contact.subtitle': 'Get in touch with us to learn how we can help you. Our expert team is ready to answer all your questions.',
    'contact.callNow': 'Call Now',
    'contact.whatsapp': 'WhatsApp',
    'contact.form.title': 'Free Consultation',
    'contact.form.subtitle': 'Fill out the form, we will get back to you as soon as possible',
    'contact.form.name': 'Your Full Name *',
    'contact.form.surname': 'Your Surname',
    'contact.form.namePlaceholder': 'Your first and last name',
    'contact.form.phone': 'Your Phone Number *',
    'contact.form.phonePlaceholder': '+90 5XX XXX XX XX',
    'contact.form.email': 'Your Email Address *',
    'contact.form.emailPlaceholder': 'example@email.com',
    'contact.form.message': 'Your Message',
    'contact.form.messagePlaceholder': 'What would you like to know about?',
    'contact.form.submit': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.optional': 'Optional',
    'contact.info.title': 'Contact Information',
    'contact.info.subtitle': 'We serve you in our modern clinic at our central location. You can reach us through the following ways to make an appointment or ask your questions.',
    'contact.info.address': 'Address',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Working Hours',
    'contact.info.phone.title': 'Phone',
    'contact.info.email.title': 'Email',
    'contact.info.address.title': 'Address',
    'contact.info.whatsapp.title': 'WhatsApp',
    'contact.info.addressLine1': 'Istanbul/Atasehir',
    'contact.info.addressLine2': '',
    'contact.info.phoneNumber': '+90 543 176 7634',
    'contact.info.workingHours': 'Monday - Saturday: 09:00 - 18:00',
    'contact.info.sunday': 'Sunday: Closed',
    'contact.info.email1': 'info@vesnahairclinic.com',
    'contact.info.email2': 'support@vesnahairclinic.com',
    'contact.location.title': 'Location',
    'contact.location.viewOnMap': 'View on Map',
    'contact.social.title': 'Social Media',
    'contact.cta.title': 'How Can We Help You?',
    'contact.cta.subtitle': 'Contact our expert team and achieve your dream hair',
    'contact.why.title': 'Why Vesna Hair Clinic?',
    'contact.why.experience': 'Experienced Team',
    'contact.why.experienceDesc': '8+ years of experience and thousands of successful operations',
    'contact.why.guarantee': 'Guaranteed Results',
    'contact.why.guaranteeDesc': 'Proven quality with 98% success rate',
    'contact.why.support': '24/7 Support',
    'contact.why.supportDesc': 'Complete support before and after the procedure',
    'contact.success.title': 'Your Message Has Been Sent Successfully! 🎉',
    'contact.success.subtitle': 'Your request has been received. Our expert team will contact you as soon as possible.',
    'contact.success.note': 'We usually get back to you within 24 hours.',
    'contact.success.callNow': 'Call Now',
    'contact.success.whatsapp': 'WhatsApp',
    'contact.success.close': 'Close',
    'contact.badge': 'Contact',
    'contact.mainTitle': 'GET IN TOUCH',
    'contact.mainSubtitle': 'Contact our expert team and achieve your dream hair',
    'contact.infoTitle': 'Contact Information',
    'contact.infoSubtitle': 'You can reach us through the most suitable communication channel',
    'contact.formTitle': 'Send Message',
    'contact.formSubtitle': 'Contact us for free consultation',
    'contact.quickCall': 'Call Now',
    'contact.quickWhatsapp': 'WhatsApp',
    'contact.quickMessage': 'Instant message',
    
    // About Page
    'about.title': 'About Us',
    'about.description': 'Vesna Hair Clinic is a healthcare institution established by combining years of experience and scientific approach in the field of hair transplantation.',
    'about.paragraph1': 'Vesna Hair Clinic is a healthcare institution established by combining years of experience and scientific approach in the field of hair transplantation. Our founders are experienced specialists who have worked in leading corporate clinics in the sector and have taken responsibility for thousands of successful operations.',
    'about.paragraph2': 'Our goal as a clinic is to provide personalized solutions to each patient and to provide natural and permanent results in line with the most current technologies and ethical principles. At Vesna Hair Clinic, all processes are carried out on the basis of patient satisfaction, hygiene standards and professionalism.',
    'about.paragraph3': 'Together with our healthcare personnel, each of whom is competent in their own field, we aim to offer not only aesthetic but also a treatment process that inspires confidence. Vesna Hair Clinic is a modern hair transplant clinic based on quality, transparency and sustainable success.',
    'about.whyUs': 'Why Choose Us?',
    'about.whyUsDesc': 'Our distinctive features in the field of hair transplantation',
    'about.feature1.title': 'Experienced Staff',
    'about.feature1.desc': 'Specialist doctors who have worked in leading clinics in the sector',
    'about.feature2.title': 'Thousands of Successful Operations',
    'about.feature2.desc': 'Thousands of successful interventions performed over the years',
    'about.feature3.title': 'Patient Satisfaction',
    'about.feature3.desc': 'Personalized solutions and a treatment process that inspires confidence',
    'about.feature4.title': 'Modern Technology',
    'about.feature4.desc': 'Service in line with the most up-to-date technologies and ethical principles',
    'about.mission': 'Our Mission',
    'about.missionDesc': 'Our mission is to provide the highest quality service in the field of hair health, increase our customers\' self-confidence and improve their quality of life. We aim to achieve natural and permanent results by offering special solutions to each patient.',
    'about.vision': 'Our Vision',
    'about.visionDesc': 'Our vision is to be a leading organization that provides services at international standards as Turkey\'s most reliable hair clinic. We want to maintain our leading position in the sector with our understanding of continuous development and innovation.',
    'about.stats.operations': 'Successful Operations',
    'about.stats.experience': 'Years Experience',
    'about.stats.satisfaction': 'Customer Satisfaction',
    'about.stats.success': 'Success Rate',
    'about.stats.support': 'Support Service',
    'about.cta.title': 'Achieve Your Dream Hair',
    'about.cta.subtitle': 'Get a free consultation from our expert team and discover the most suitable treatment plan for you',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'Our mission is to provide the highest quality service in the field of hair health, increase our customers\' self-confidence and improve their quality of life.',
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'Our vision is to be a leading organization that provides services at international standards as Turkey\'s most reliable hair clinic.',
    
    // Before After Page
    'beforeAfter.title': 'Before / After',
    'beforeAfter.subtitle': 'Explore our successful hair transplant results and see the power of transformation',
    'beforeAfter.before': 'BEFORE',
    'beforeAfter.after': 'AFTER',
    'beforeAfter.heroSubtitle': 'Our Successful Results',
    'beforeAfter.heroDescription': '',
    'beforeAfter.heroDescriptionHighlight': '',
    'beforeAfter.realResults': 'Real Results',
    'beforeAfter.realResultsDesc': '',
    'beforeAfter.ctaTitle1': 'Your Dream Hair',
    'beforeAfter.ctaTitle2': 'Start Today',
    'beforeAfter.ctaSubtitle': 'Get your free consultation with our expert team and',
    'beforeAfter.ctaSubtitleHighlight': 'start writing your own success story.',
    'beforeAfter.nextYou': 'You\'re Next',
    'beforeAfter.callNow': 'Call Now',
    'beforeAfter.whatsapp': 'WhatsApp',
    'beforeAfter.stat1': 'Happy Patients',
    'beforeAfter.stat2': 'Satisfaction',
    'beforeAfter.stat3': 'Years Experience',
    'beforeAfter.stat4': 'Support',
    'beforeAfter.trust1': '3800+ Happy Patients',
    'beforeAfter.trust1Desc': 'Successful operations',
    'beforeAfter.trust2': '98% Success Rate',
    'beforeAfter.trust2Desc': 'Proven quality',
    'beforeAfter.trust3': '24/7 Support',
    'beforeAfter.trust3Desc': 'Continuous service',
    'beforeAfter.result1': 'Amazing Transformation',
    'beforeAfter.result2': 'Natural Results',
    'beforeAfter.result3': 'Dream Hair Achieved',
    'beforeAfter.result4': 'Perfect Results',
    'beforeAfter.result5': 'Dense and Natural',
    'beforeAfter.result6': 'Impressive Change',
    'beforeAfter.result7': 'Perfect Hairline',
    'beforeAfter.result8': 'Young and Dynamic',
    'beforeAfter.result9': 'Exactly as Desired',
    'beforeAfter.satisfied': 'satisfied',
    
    // Common
    'common.getInfo': 'Get Info',
    'common.freeConsultation': 'Free Consultation',
    'common.appointment': 'Book Appointment',
    'common.settings': 'Settings',
    'common.loading': 'Loading...',
    'common.sending': 'Sending...',
    'common.send': 'Send',
    'common.before': 'BEFORE',
    'common.after': 'AFTER',
    'common.hairTransplantResults': 'Hair Transplant Results',
    'common.hours': 'hours',
    'common.minutes': 'minutes',
    
    // Footer
    'footer.description': 'Let\'s achieve your dream hair together. Our team is ready to answer all your questions and accompany you on your journey to fuller, natural-looking hair.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.certificate': 'Health Certificate',
    'footer.rights': 'All rights reserved.',
    'footer.about': 'About Us',
    'footer.address': 'Address',
    'footer.workingHours': 'Working Hours',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterDesc': 'Stay updated with news',
    'footer.emailPlaceholder': 'Your email address',
    'footer.subscribe': 'Subscribe',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    
    // WhatsApp
    'whatsapp.contact': 'Contact via WhatsApp',
    
    // FAQ Section (Services Page)
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Answers to questions about hair transplantation',
    'faq.question1': 'Is hair transplant painful?',
    'faq.answer1': 'Hair transplant performed with local anesthesia is completely painless. Only slight discomfort is felt during anesthesia.',
    'faq.question2': 'When can I see the results?',
    'faq.answer2': 'First results start to be seen after 6-8 months. Full results appear within 12-18 months.',
    'faq.question3': 'How is the healing process?',
    'faq.answer3': 'Rest is recommended for the first 3 days. Healing is completed within 7-10 days as scabs fall off.',
    'faq.question4': 'Is it permanent or will it fall out again?',
    'faq.answer4': 'Hair taken from the nape area is genetically resistant to shedding and is permanent.',
    'faq.question5': 'Is there an age limit?',
    'faq.answer5': 'Suitable for anyone over the age of 18. An examination is recommended for definitive results.',
    'faq.question6': 'How are prices determined?',
    'faq.answer6': 'It is determined in line with the technique to be used and the personalized planning.',

    // Instagram Section (Contact Page)
    'instagram.title': 'Follow Us on Instagram',
    'instagram.subtitle': 'Follow us on Instagram for the latest news, patient stories and clinic updates',
    'instagram.description': 'Follow us on Instagram for our latest hair transplant results, patient stories and clinic updates! ✨',
    'instagram.followButton': 'Follow on Instagram',
    'instagram.postNumber': 'Post #',
    'instagram.loading': 'Loading posts...',
    'instagram.postAlt': 'Instagram post',
    'common.reels': 'REELS',
    'common.viewPost': 'View',
    

    // 404 Page
    '404.title': 'Page Not Found',
    '404.description': 'The page you are looking for might have been moved, deleted, or is temporarily unavailable.',
    '404.backHome': 'Back to Home',
    '404.contact': 'Contact',
    '404.needHelp': 'Need Help?',
    '404.popularLinks': 'Popular Links',
    '404.searchPlaceholder': 'Type the page you are looking for...',
    '404.helpTitle': 'Need Help?',
    '404.helpDescription': 'Let us help you right away',
    '404.phone': 'Phone',
    '404.instantMessage': 'Instant Message',
    '404.tip': '💡 Tip: You can navigate directly to pages by typing "about", "services" or "contact" in the search box'
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('tr')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'tr' || savedLanguage === 'en')) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  const toggleLanguage = () => {
    handleSetLanguage(language === 'tr' ? 'en' : 'tr')
  }

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
} 